# Generated by Django 4.0.1 on 2022-03-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_rename_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='company',
            new_name='teacher',
        ),
    ]
