# Generated by Django 4.0.1 on 2022-03-25 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_rename_teacher_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
