# Generated by Django 4.0.1 on 2022-03-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_group_alter_customuser_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='AA-87', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(default='Null', max_length=30),
        ),
    ]
