# Generated by Django 4.0.1 on 2022-03-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_slug_alter_customuser_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(default='', max_length=30),
        ),
    ]
