# Generated by Django 4.0.1 on 2022-03-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_customuser_slug_alter_customuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
